# Week 05 - Dask Programming Assignment
Date : 02-23-2025 <br>
Author : Daipayan Bera

In [142]:
#Importing libraries
import dask.dataframe as dd
import pandas as pd
import numpy as np

1. Obtain the dataset from here: https://coronadatascraper.com/timeseries.csv.zip. Details and some interesting work associated with it is found here: https://coronadatascraper.com/#home
2. Extract the .csv file from the zipped archive, and load it into a Dask dataframe.

In [143]:
covid_dd = dd.read_csv("https://coronadatascraper.com/timeseries.csv", dtype={'name':str,'level':str,'city':object,'county':str,'state':str,'country':str,'population':np.float64,'lat':float,'long':float,'url':str,'aggregate':object,'tz':str,'cases':np.float64,'deaths':np.float64,'recovered':np.float64,'active':np.float64,'tested':np.float64,'hospitalized':np.float64,'hospitalized_current':np.float64,'discharged':np.float64,'icu':np.float64,'icu_current':np.float64,'growthFactor':np.float64,'date':object})

Please note: This dataset only consists of a total of 7 months in 2020 (January-July) and not 14 months as described in the statement. While American Samoa, Guam, Northern Mariana Islands, Puerto Rico, and Virgin Islands don't exactly come under the US, as it is stated in the dataset, therefore I didn't omit it.

3.1. Create a new dataframe object that consists of samples (i.e., rows) corresponding to states in the US.

In [144]:
us_df = covid_dd.query("country == 'United States'")
us_df = us_df.persist() #Using persist after the query as we are going to use this dask dataframe throughout this workfile

3.2. During the time period 2020-Jan-01 to 2021-Feb-28, rank states in terms of their per-capita mortality? Compute per-capita mortality during a specific period as the ratio of total deaths during that time period, to the average population of the state (compute the average population during the time period).

In [146]:
#The following code is going to use the dask dataframe us_df, therefore it is going to be executed parallelly
agg_df = us_df.groupby("state").agg({
    "population" : "mean",
    "deaths" : "sum"
})

state_df = agg_df.compute() #As we are saving the result as a pandas dataframe therefore, we don't need to use persist
state_df["Per-capita-death"] = state_df["deaths"]/state_df["population"]

In [147]:
state_df.sort_values("Per-capita-death", ascending=False)[["Per-capita-death"]]

                              Per-capita-death
state
New York                              6.395701
Michigan                              3.204753
Louisiana                             2.735288
Illinois                              2.043863
New Jersey                            2.031200
Georgia                               2.026085
Pennsylvania                          1.831572
Virginia                              1.359063
Mississippi                           1.356705
Indiana                               1.353423
Ohio                                  1.058943
Iowa                                  0.958771
Massachusetts                         0.904775
Colorado                              0.894296
Minnesota                             0.768853
Kentucky                              0.751512
Texas                                 0.737643
Missouri                              0.711146
Connecticut                           0.677952
Maryland                              0.658347
Alabama                               0.599759
North Carolina                        0.549190
Florida                               0.545793
Wisconsin                             0.437617
Nebraska                              0.397699
Oklahoma                              0.397603
Tennessee                             0.375231
California                            0.371347
Washington                            0.359377
Kansas                                0.330341
New Mexico                            0.327128
South Carolina                        0.315557
Arkansas                              0.271762
Rhode Island                          0.220419
South Dakota                          0.215476
North Dakota                          0.204487
West Virginia                         0.136558
Nevada                                0.126360
New Hampshire                         0.123780
Idaho                                 0.118306
Vermont                               0.101814
Oregon                                0.098453
Delaware                              0.095738
Maine                                 0.077630
Washington, D.C.                      0.045661
Utah                                  0.044994
Wyoming                               0.028398
Arizona                               0.028349
Montana                               0.025902
Alaska                                0.019541
United States Virgin Islands          0.002364
Northern Mariana Islands              0.001922
Hawaii                                0.001786
Puerto Rico                           0.001670
Guam                                  0.001585
American Samoa                        0.000000

3.3. During the same time period, compute the case fatality rate (CFR) per month, using one of the approaches defined in this scientific brief from the World Health Organization: https://www.who.int/news-room/commentaries/detail/estimating-mortality-from-covid-19Links to an external site.. This computation should yield an array of dimensions 50 (states) X 14 (months). State the assumptions you are making in computing this metric.

In [148]:
#The following code is going to use the dask dataframe us_df, therefore it is going to be executed parallelly
us_df["date"] = dd.to_datetime(us_df["date"])
us_df["month_year"] = us_df["date"].dt.strftime("%B %Y")

agg_us_df = us_df.groupby(["state","month_year"]).agg({
    "deaths": "sum",
    "cases": "sum"  
})

CFR = agg_us_df.compute() #Here, we can use compute directly without using persist as we won't be reusing this again

In [149]:
CFR["cfr_val"] = (CFR["deaths"]*100/CFR["cases"]).fillna(0)

In [150]:
pivot_CFR = CFR.pivot_table(index="state", columns="month_year", values="cfr_val").fillna(0)

In [151]:
#Printing out the result
pivot_CFR

month_year,April 2020,February 2020,January 2020,July 2020,June 2020,March 2020,May 2020
state,,,,,,,
Alabama,2.830899,0.000000,0.0,2.381771,2.962907,0.532313,3.889270
Alaska,2.314519,0.000000,0.0,1.207417,1.303247,0.335008,2.196905
American Samoa,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
Arizona,1.486545,0.000000,0.0,0.973523,0.211513,0.000000,1.992175
Arkansas,1.911450,0.000000,0.0,1.274360,1.515155,0.915656,2.129628
California,3.479974,0.000000,0.0,2.543001,3.178666,2.006735,3.983350
Colorado,2.636616,0.000000,0.0,5.063691,5.419220,0.939250,5.372019
Connecticut,6.477626,0.000000,0.0,9.500807,9.383106,1.814771,9.016204
Delaware,2.734038,0.000000,0.0,4.013148,4.164733,1.334107,3.574849
Florida,2.905738,0.000000,0.0,2.039752,3.404313,0.842669,4.277250
Georgia,3.980977,0.000000,0.0,3.263239,4.312292,2.185574,4.452969
Guam,3.615483,0.000000,0.0,1.774308,2.750275,2.702703,3.186275
Hawaii,0.000000,0.000000,0.0,0.000000,1.923594,0.036271,0.481140
Idaho,2.258980,0.000000,0.0,1.385931,2.255316,1.448967,3.026976
Illinois,4.048394,0.000000,0.0,4.802791,4.760111,1.288155,4.427381
Indiana,4.775795,0.000000,0.0,5.314359,5.849879,2.396460,5.564376
Iowa,2.326472,0.000000,0.0,2.364454,2.682311,0.863465,2.433142
Kansas,2.364135,0.000000,0.0,1.781868,1.998686,0.989866,1.423958
Kentucky,5.074331,0.000000,0.0,3.706810,4.045568,2.225112,4.666360
Louisiana,5.191232,0.000000,0.0,5.138853,6.157174,3.916843,7.010445
Maine,3.778067,0.000000,0.0,3.156923,3.583397,0.529355,4.182856
Maryland,3.684368,0.000000,0.0,4.649307,4.670979,0.261008,4.806133
Massachusetts,4.415282,0.000000,0.0,7.437951,7.247411,0.499505,6.625696
Michigan,7.508176,0.000000,0.0,8.623360,9.097596,2.493512,9.902791
Minnesota,2.527566,0.000000,0.0,3.958075,4.173187,0.000000,3.052268
Mississippi,3.296058,0.000000,0.0,3.743453,4.455260,1.504930,4.593225
Missouri,2.878952,0.000000,0.0,3.979086,5.578889,1.196568,4.774436
Montana,0.966368,0.000000,0.0,1.555189,2.792962,0.000000,2.283996
Nebraska,1.422412,0.000000,0.0,1.443365,1.359915,0.000000,1.257609
Nevada,4.051924,0.000000,0.0,2.541570,3.830004,2.033319,4.970358
New Hampshire,1.546978,0.000000,0.0,6.436738,5.992573,0.268757,4.025026
New Jersey,4.064989,0.000000,0.0,8.251406,7.773725,0.401749,6.934022
New Mexico,2.949834,0.000000,0.0,4.003795,4.409418,0.705290,4.336271
New York,6.525716,0.000000,0.0,7.233961,7.321241,2.075213,7.365287
North Carolina,2.722044,0.000000,0.0,1.987512,2.512702,0.331498,3.471947
North Dakota,0.893946,0.000000,0.0,2.215880,2.194075,0.253646,1.346565
Northern Mariana Islands,14.468085,0.000000,0.0,6.535948,7.042254,0.000000,10.569106
Ohio,4.404734,0.000000,0.0,5.275945,6.024960,1.529431,5.865587
Oklahoma,5.439956,0.000000,0.0,2.656809,3.909534,2.833876,5.568855
Oregon,3.617323,0.000000,0.0,2.237008,2.944807,2.660322,3.837110
Pennsylvania,3.292275,0.000000,0.0,7.418973,7.506220,1.081428,6.835164
Puerto Rico,5.808946,0.000000,0.0,1.998391,2.773468,0.000000,4.524982
Rhode Island,1.516496,0.000000,0.0,5.821287,5.476087,0.061703,3.314532
South Carolina,2.882223,0.000000,0.0,1.922291,2.894657,1.964286,4.344983
South Dakota,0.453175,0.000000,0.0,1.383357,1.282311,0.775194,1.074754
Tennessee,1.964376,0.000000,0.0,1.302543,1.513466,0.036523,1.655256
Texas,2.403974,0.000000,0.0,1.392601,2.009166,1.184979,2.737519
United States Virgin Islands,5.223881,0.000000,0.0,5.976096,8.379888,0.000000,7.835400
Utah,0.446306,0.000000,0.0,0.362686,0.808203,0.179292,0.630986
Vermont,4.238581,0.000000,0.0,4.559147,4.977477,3.411633,5.710436
Virginia,2.865308,0.000000,0.0,2.841844,2.862225,1.406402,3.315829
Washington,5.255217,1.360544,0.0,3.921734,4.396312,5.051079,5.308562
"Washington, D.C.",3.736434,0.000000,0.0,5.330110,5.289760,1.436880,5.264651
West Virginia,2.181204,0.000000,0.0,3.004665,3.638010,0.000000,3.136926
Wisconsin,4.482942,0.000000,0.0,2.495788,2.998631,0.852336,3.625332
Wyoming,0.396069,0.000000,0.0,0.634035,1.514208,0.000000,0.779409

3.4. Using this matrix as input, compute the ranking of states, on how the CFR rate changed over time. This computation will involve an aggregation of of month-to-month changes in CFR. Note that some of these month-to-month changes can be positive (CFR increases from a previous month to the current month) or negative (CFR decrease from a previous month to the current month), or zero (no change in CFR). You need to aggregate these individual changes, across all time periods.

In [152]:
#Reordering the month columns
pivot_CFR = pivot_CFR[["January 2020", "February 2020", "March 2020", "April 2020", "May 2020", "June 2020", "July 2020"]]

In [153]:
#Using diff function on each column, then summarizing with sum function and applying sorting in descending order
pivot_CFR.diff(axis=1).sum(axis=1).sort_values(ascending=False)

state
Connecticut                     9.500807
Michigan                        8.623360
New Jersey                      8.251406
Massachusetts                   7.437951
Pennsylvania                    7.418973
New York                        7.233961
Northern Mariana Islands        6.535948
New Hampshire                   6.436738
United States Virgin Islands    5.976096
Rhode Island                    5.821287
Washington, D.C.                5.330110
Indiana                         5.314359
Ohio                            5.275945
Louisiana                       5.138853
Colorado                        5.063691
Illinois                        4.802791
Maryland                        4.649307
Vermont                         4.559147
Delaware                        4.013148
New Mexico                      4.003795
Missouri                        3.979086
Minnesota                       3.958075
Washington                      3.921734
Mississippi                     3.743453
Kentucky                        3.706810
Georgia                         3.263239
Maine                           3.156923
West Virginia                   3.004665
Virginia                        2.841844
Oklahoma                        2.656809
California                      2.543001
Nevada                          2.541570
Wisconsin                       2.495788
Alabama                         2.381771
Iowa                            2.364454
Oregon                          2.237008
North Dakota                    2.215880
Florida                         2.039752
Puerto Rico                     1.998391
North Carolina                  1.987512
South Carolina                  1.922291
Kansas                          1.781868
Guam                            1.774308
Montana                         1.555189
Nebraska                        1.443365
Texas                           1.392601
Idaho                           1.385931
South Dakota                    1.383357
Tennessee                       1.302543
Arkansas                        1.274360
Alaska                          1.207417
Arizona                         0.973523
Wyoming                         0.634035
Utah                            0.362686
Hawaii                          0.000000
American Samoa                  0.000000
dtype: float64

4. For each of the above operations, explain using appropriate reasoning, whether using a parallelized and/or distributed way of performing the computation makes sense.

In this exercise, I used parallelized tasks with Dask for certain computations, while relying on sequential execution for the rest, as it was more efficient in those cases. As per the computation graph that we saw in the lecture video (dask2-3.mp4 - By Dr. Mudigonda) helped illustrate when parallelized or distributed computing should be leveraged—specifically when the dataset is too large to fit into local memory or when the computation is highly CPU-intensive.

In this case, even though the dataset could easily fit into local memory, the computations could still have been time-consuming if we had to query the dataset repeatedly. To address this, I utilized parallelized operations through Dask during data querying and aggregation, as these tasks tend to be the most computation-heavy.

Additionally, I used Dask's persist() method after querying the Dask DataFrame to ensure that the query results are not recomputed multiple times when needed. This approach optimized performance by storing intermediate results in memory. If the dataset had been significantly larger, a distributed cluster could have been used to scale the computations further.